version: '3'

volumes:
  api-db-data:
services:
  qgisserver:
    depends_on:
      - apidb
    build: ./
    volumes:
      - ./:/var/www/plugins/ProjectReloader
      - ./tests:/project/
    ports:
      - 8380:80
    environment:
      - QGIS_SERVER_LOG_LEVEL=0
      - PYTHONPATH=/usr/local/share/qgis/python/qgis/
      #- QGIS_PROJECT_FILE=postgresql://nxo:nxo@apidb:5432?sslmode=disable&dbname=nxo&schema=public&project=test2

  apidb:
      image: mdillon/postgis:11-alpine
      ports:
        - "54332:5432"
      env_file:
        - config.env
      volumes:
        - api-db-data:/var/lib/postgresql
