version: '3.4'

services:
  qgisserver:
    image: qgis/qgis:release-3_12
    depends_on:
      - db
    volumes:
      - ./ProjectReloader/:/var/www/plugins/ProjectReloader
      - ./tests/data:/data
    environment:
      - QGIS_PLUGINPATH=/var/www/plugins
      - QGIS_SERVER_LOG_LEVEL=0
    ports:
      - 8000:8000
    command:
      - "qgis_mapserver"

  db:
    image: mdillon/postgis:11-alpine
    environment:
      - PGPORT=5432
      - POSTGRES_USER=qgis
      - POSTGRES_PASSWORD=qgis
      - POSTGRES_DB=qgis

  tester:
    build:
      context: ./
      target: tester
    volumes:
      - ./tests:/tests
      - ./tests/data:/data
    environment:
      - PYTHONPATH=/usr/local/share/qgis/python/qgis/
